In [102]:
import pandas as pd
import numpy as np
import datetime as dt

In [103]:
path = r'C:\Users\Elizaveta\Documents\ТПШ_2021\data_1\\'
# def read(fname):
#     return pd.read_csv(path + fname, encoding = 'utf-16', sep = ',')

In [104]:
text = pd.read_csv('texttimecount.csv')
video = pd.read_csv('videotimecount.csv')
audio = pd.read_csv('audiotimecount.csv')

In [105]:
text.columns, video.columns, audio.columns

(Index(['reader_id', 'content_id', 'time_spent'], dtype='object'),
 Index(['user_id', 'content_id', 'time_spend', 'title'], dtype='object'),
 Index(['viewer_id', 'content_id', 'viewtime'], dtype='object'))

In [106]:
text = text.rename(columns={'reader_id': 'user_id', 'time_spent':'time_spend'})
audio = audio.rename(columns={'viewer_id': 'user_id', 'viewtime': 'time_spend'})

In [107]:
video = video.drop('title', axis=1)
video

,user_id,content_id,time_spend
0,00007F8B-D3F1-45E5-87BC-8474A06A1513,382F7490-AF9C-4C51-9E57-6B5AFC8404E5,0 days 00:00:20
1,00007F8B-D3F1-45E5-87BC-8474A06A1513,DAE1611E-079D-4FF9-BA1C-E9C0A0DCB469,0 days 00:33:22
2,00007F8B-D3F1-45E5-87BC-8474A06A1513,FDA21E1E-53CF-44DE-A566-2DA941E6F410,0 days 00:10:15
3,0000F1DE-F492-4666-B260-791755DD45D0,3AB399DC-CFFE-42D6-B9F7-C4417C8DAF3F,0 days 00:16:57
4,000532C1-FB16-44AD-B1C4-60EF7E12DE45,08161169-2BF7-4B87-8BF0-3D5F8E4D9BAD,0 days 00:06:24
...,...,...,...
65299,FFF4328A-F0A4-4345-9E58-135A814C7765,6B0DF955-3142-40E3-9C7D-4ABDEE03B241,0 days 00:01:57
65300,FFF5A52C-EBAD-4200-97F4-F10931AE4144,0A7EBD6F-743A-4F35-A7FC-29D9462E7D24,0 days 00:58:54
65301,FFF5A52C-EBAD-4200-97F4-F10931AE4144,8899F90F-6989-4E31-BD27-36EFDCB49743,0 days 00:06:43
65302,FFF745DE-001E-4446-9BFC-8DB95EF10689,75E4A4AA-4E65-4959-8508-6DB9AD95217E,0 days 00:04:21
65303,FFF97A39-1959-4A25-AFAE-0C2F0DDCE2D4,7E5DA497-6661-4772-A891-0C4B0968FE57,0 days 00:01:31

In [108]:
audio

,user_id,content_id,time_spend
0,00AD69AA-8C1A-4BA4-9221-24AF0AC92A38,13BCAB7C-D84E-46E7-B99C-EA589B880F5D,0 days 00:00:11
1,00AD69AA-8C1A-4BA4-9221-24AF0AC92A38,3102750F-D246-47CE-AC5E-1701A1BFD1EB,0 days 00:00:09
2,00AD69AA-8C1A-4BA4-9221-24AF0AC92A38,378DC398-7211-4498-89EA-C40088563C0D,0 days 00:01:03
3,00AD69AA-8C1A-4BA4-9221-24AF0AC92A38,BD0A962E-13ED-4054-9920-45912B4C59BE,0 days 00:00:11
4,00AD69AA-8C1A-4BA4-9221-24AF0AC92A38,E5D7A079-2A15-47D6-A261-B7C8A977AC8F,0 days 00:04:56
...,...,...,...
555,FA46154A-0CB5-4F32-B1BA-D1EB81D2C554,415FF938-49CB-4356-A538-7C552569CBE1,0 days 00:09:17
556,FB828D5B-D0B9-42CF-A8AA-7C5C60860776,2A0CEE32-9B76-48A9-BCB9-1AF99E7B9DDE,0 days 00:11:37
557,FC61FCB9-F606-4930-80AC-D4FE5B9E87D0,5964F5AF-7DB6-44A0-812B-527A36890184,0 days 00:02:21
558,FD4D1163-5770-495F-ABCD-7D1456DE40AA,1B6BC77C-3201-4CE0-8007-9C57EAD1B7C2,0 days 00:00:03
559,FD72D010-BC42-4597-A9F9-458E83BE911E,CF56E5A4-EEFE-4275-8B56-F7F15A98D423,0 days 00:24:19

In [109]:
audio = audio.rename(columns={'time_spend': 'audio_time_spend'})
video = video.rename(columns={'time_spend': 'video_time_spend'})
text = text.rename(columns={'time_spend': 'text_time_spend'})

In [110]:
audio = audio.set_index(['user_id', 'content_id'])
video = video.set_index(['user_id', 'content_id'])
text = text.set_index(['user_id', 'content_id'])

In [111]:
# audio = audio.set_index('user_id')
# video = video.set_index('user_id')
# text = text.set_index('user_id')

In [112]:
general = video.join(audio)
general = general.join(text)
general['audio_time_spend'] = general.audio_time_spend.fillna(pd.Timedelta(0))
general['text_time_spend'] = general.text_time_spend.fillna(pd.Timedelta(0))
general['video_time_spend'] = general.video_time_spend.fillna(pd.Timedelta(0))

In [113]:
general['time_spend'] = general['audio_time_spend'] + general['text_time_spend'] + general['video_time_spend']

In [114]:
general.to_csv('text_audio_video_time_spend.csv')

In [115]:
general

                                                                          video_time_spend  \
user_id                              content_id
00007F8B-D3F1-45E5-87BC-8474A06A1513 382F7490-AF9C-4C51-9E57-6B5AFC8404E5  0 days 00:00:20
                                     DAE1611E-079D-4FF9-BA1C-E9C0A0DCB469  0 days 00:33:22
                                     FDA21E1E-53CF-44DE-A566-2DA941E6F410  0 days 00:10:15
0000F1DE-F492-4666-B260-791755DD45D0 3AB399DC-CFFE-42D6-B9F7-C4417C8DAF3F  0 days 00:16:57
000532C1-FB16-44AD-B1C4-60EF7E12DE45 08161169-2BF7-4B87-8BF0-3D5F8E4D9BAD  0 days 00:06:24
...                                                                                    ...
FFF4328A-F0A4-4345-9E58-135A814C7765 6B0DF955-3142-40E3-9C7D-4ABDEE03B241  0 days 00:01:57
FFF5A52C-EBAD-4200-97F4-F10931AE4144 0A7EBD6F-743A-4F35-A7FC-29D9462E7D24  0 days 00:58:54
                                     8899F90F-6989-4E31-BD27-36EFDCB49743  0 days 00:06:43
FFF745DE-001E-4446-9BFC-8DB95EF10689 75E4A4AA-4E65-4959-8508-6DB9AD95217E  0 days 00:04:21
FFF97A39-1959-4A25-AFAE-0C2F0DDCE2D4 7E5DA497-6661-4772-A891-0C4B0968FE57  0 days 00:01:31

                                                                          audio_time_spend  \
user_id                              content_id
00007F8B-D3F1-45E5-87BC-8474A06A1513 382F7490-AF9C-4C51-9E57-6B5AFC8404E5  0 days 00:00:00
                                     DAE1611E-079D-4FF9-BA1C-E9C0A0DCB469  0 days 00:00:00
                                     FDA21E1E-53CF-44DE-A566-2DA941E6F410  0 days 00:00:00
0000F1DE-F492-4666-B260-791755DD45D0 3AB399DC-CFFE-42D6-B9F7-C4417C8DAF3F  0 days 00:00:00
000532C1-FB16-44AD-B1C4-60EF7E12DE45 08161169-2BF7-4B87-8BF0-3D5F8E4D9BAD  0 days 00:00:00
...                                                                                    ...
FFF4328A-F0A4-4345-9E58-135A814C7765 6B0DF955-3142-40E3-9C7D-4ABDEE03B241  0 days 00:00:00
FFF5A52C-EBAD-4200-97F4-F10931AE4144 0A7EBD6F-743A-4F35-A7FC-29D9462E7D24  0 days 00:00:00
                                     8899F90F-6989-4E31-BD27-36EFDCB49743  0 days 00:00:00
FFF745DE-001E-4446-9BFC-8DB95EF10689 75E4A4AA-4E65-4959-8508-6DB9AD95217E  0 days 00:00:00
FFF97A39-1959-4A25-AFAE-0C2F0DDCE2D4 7E5DA497-6661-4772-A891-0C4B0968FE57  0 days 00:00:00

                                                                           text_time_spend  \
user_id                              content_id
00007F8B-D3F1-45E5-87BC-8474A06A1513 382F7490-AF9C-4C51-9E57-6B5AFC8404E5  0 days 00:00:00
                                     DAE1611E-079D-4FF9-BA1C-E9C0A0DCB469  0 days 00:00:00
                                     FDA21E1E-53CF-44DE-A566-2DA941E6F410  0 days 00:00:00
0000F1DE-F492-4666-B260-791755DD45D0 3AB399DC-CFFE-42D6-B9F7-C4417C8DAF3F  0 days 00:00:00
000532C1-FB16-44AD-B1C4-60EF7E12DE45 08161169-2BF7-4B87-8BF0-3D5F8E4D9BAD  0 days 00:00:00
...                                                                                    ...
FFF4328A-F0A4-4345-9E58-135A814C7765 6B0DF955-3142-40E3-9C7D-4ABDEE03B241  0 days 00:00:00
FFF5A52C-EBAD-4200-97F4-F10931AE4144 0A7EBD6F-743A-4F35-A7FC-29D9462E7D24  0 days 00:00:00
                                     8899F90F-6989-4E31-BD27-36EFDCB49743  0 days 00:00:00
FFF745DE-001E-4446-9BFC-8DB95EF10689 75E4A4AA-4E65-4959-8508-6DB9AD95217E  0 days 00:00:00
FFF97A39-1959-4A25-AFAE-0C2F0DDCE2D4 7E5DA497-6661-4772-A891-0C4B0968FE57  0 days 00:00:00

                                                                                time_spend
user_id                              content_id
00007F8B-D3F1-45E5-87BC-8474A06A1513 382F7490-AF9C-4C51-9E57-6B5AFC8404E5  0 days 00:00:20
                                     DAE1611E-079D-4FF9-BA1C-E9C0A0DCB469  0 days 00:33:22
                                     FDA21E1E-53CF-44DE-A566-2DA941E6F410  0 days 00:10:15
0000F1DE-F492-4666-B260-791755DD45D0 3AB399DC-CFFE-42D6-B9F7-C4417C8DAF3F  0 days 00:16:57
000532C1-FB16-44AD-B1C4-60EF7E12DE45 08161169-2BF7-4B87-8BF0-3D5F8E4D9BAD  0 days 00:06:24
...                                                                                    ...
FFF4328A-F0A4-4345-9E58-135A814C7765 6B0DF955-3142-40E3-9C7D-4ABDEE03B241  0 days 00:01:57
FFF5A52C-EBAD-4200-97F4-F10931AE4144 0A7EBD6F-743A-4F35-A7FC-29D9462E7D24  0 days 00:58:54
                                     8899F90F-6989-4E31-BD27-36EFDCB49743  0 days 00:06:43
FFF745DE-001E-4446-9BFC-8DB95EF10689 75E4A4AA-4E65-4959-8508-6DB9AD95217E  0 days 00:04:21
FFF97A39-1959-4A25-AFAE-0C2F0DDCE2D4 7E5DA497-6661-4772-A891-0C4B0968FE57  0 days 00:01:31

[65304 rows x 4 columns]